In [22]:
import numpy as np

In [23]:
arr = np.random.randn(3, 5)

In [24]:
arr

array([[-0.72997596,  0.67178551,  0.56110416, -0.21982167, -1.32055722],
       [ 0.40282537, -0.31948716, -0.66597285,  0.14961019, -0.1347414 ],
       [-0.95211788, -1.333932  , -0.67991766, -0.54976823,  0.98191316]])

In [25]:
U, S, Vh = np.linalg.svd(arr)

In [26]:
# U should be the eigenvector of arr * arr.transpose (3 x 3)
# the columns are orttorgnal.
U

array([[-0.5766669 ,  0.7501474 ,  0.32362659],
       [ 0.13114129, -0.30599495,  0.94295761],
       [ 0.8063853 ,  0.58621325,  0.07808186]])

In [28]:
np.isclose(np.dot(U[:, 0], U[:, 1]), 0)

True

In [29]:
np.isclose(np.dot(U[:, 1], U[:, 2]), 0)

True

In [30]:
np.isclose(np.dot(U[:, 0], U[:, 2]), 0)

True

In [33]:
S # The square root of eigenvalues for arr * arr.T

array([2.39118401, 1.42049637, 0.72014501])

In [31]:
eigvalue, eigenvec = np.linalg.eig(np.matmul(arr, arr.T))

In [32]:
eigvalue ** 0.5

array([2.39118401, 1.42049637, 0.72014501])

In [34]:
np.allclose(eigvalue ** 0.5, S)

True

In [35]:
eigenvec

array([[-0.5766669 ,  0.7501474 , -0.32362659],
       [ 0.13114129, -0.30599495, -0.94295761],
       [ 0.8063853 ,  0.58621325, -0.07808186]])

In [36]:
np.allclose(U, eigenvec)

False

In [38]:
np.matmul(np.matmul(arr, arr.T), eigenvec[:, 2:3]) / eigenvec[:, 2:3]

array([[0.51860884],
       [0.51860884],
       [0.51860884]])

In [39]:
np.matmul(np.matmul(arr, arr.T), U[:, 2:3]) / U[:, 2:3]

array([[0.51860884],
       [0.51860884],
       [0.51860884]])

In [42]:
# V is the eigenvector for arr.T@arr, Vh is the transpose of V
Vh

array([[-0.12294907, -0.62937757, -0.4011328 , -0.1241816 ,  0.64221399],
       [-0.86518785, -0.12690564,  0.15918268, -0.37519282, -0.26312765],
       [ 0.09618129, -0.26107392, -0.69358972,  0.03750495, -0.66341257],
       [-0.46509045,  0.19349671, -0.21397597,  0.82726067,  0.12690136],
       [ 0.10379563, -0.69439057,  0.53563134,  0.39754551, -0.24920842]])

In [45]:
for i in range(4):
    for j in range(i + 1, 5):
        print(np.isclose(np.dot(Vh[i], Vh[j]), 0))

True
True
True
True
True
True
True
True
True
True


In [46]:
V_val, V_vec = np.linalg.eig(np.matmul(arr.T, arr))

In [47]:
V_val

array([ 5.71776097e+00+0.00000000e+00j,  2.01780994e+00+0.00000000e+00j,
        5.18608839e-01+0.00000000e+00j, -1.41265770e-16+3.55120743e-16j,
       -1.41265770e-16-3.55120743e-16j])

In [48]:
np.allclose(V_val[:3] ** 0.5, S)

True

In [49]:
S

array([2.39118401, 1.42049637, 0.72014501])

In [50]:
V_val[:3] ** 0.5

array([2.39118401+0.j, 1.42049637+0.j, 0.72014501+0.j])

In [55]:
np.allclose(np.real(V_vec.T), Vh)

False

In [56]:
np.real(V_vec.T)

array([[-0.12294907, -0.62937757, -0.4011328 , -0.1241816 ,  0.64221399],
       [-0.86518785, -0.12690564,  0.15918268, -0.37519282, -0.26312765],
       [-0.09618129,  0.26107392,  0.69358972, -0.03750495,  0.66341257],
       [-0.28151675, -0.09906984,  0.03245054,  0.69400857,  0.00348095],
       [-0.28151675, -0.09906984,  0.03245054,  0.69400857,  0.00348095]])

In [54]:
Vh

array([[-0.12294907, -0.62937757, -0.4011328 , -0.1241816 ,  0.64221399],
       [-0.86518785, -0.12690564,  0.15918268, -0.37519282, -0.26312765],
       [ 0.09618129, -0.26107392, -0.69358972,  0.03750495, -0.66341257],
       [-0.46509045,  0.19349671, -0.21397597,  0.82726067,  0.12690136],
       [ 0.10379563, -0.69439057,  0.53563134,  0.39754551, -0.24920842]])

In [57]:
tmp = V_vec.T

for i in range(4):
    for j in range(i + 1, 5):
        print(np.isclose(np.dot(tmp[i], tmp[j]), 0))

True
True
True
True
True
True
True
True
True
False


In [58]:
arr = np.random.randn(6, 3)

In [59]:
U, S, Vh = np.linalg.svd(arr)

In [60]:
U

array([[ 0.14769479,  0.18402985, -0.71789548,  0.37428612,  0.53664019,
        -0.02953888],
       [-0.15577835,  0.76699106, -0.26061696, -0.25201778, -0.40938853,
        -0.29736289],
       [ 0.5050156 , -0.28664028, -0.1356382 ,  0.37008366, -0.50776481,
        -0.49961171],
       [-0.12148567,  0.41357805,  0.46007855,  0.76840017, -0.02293065,
         0.1075059 ],
       [ 0.66621384,  0.317233  ,  0.4017684 , -0.2610797 ,  0.41462322,
        -0.23244238],
       [ 0.49018257,  0.15495645, -0.15879873, -0.02887194, -0.33786831,
         0.77168901]])

In [61]:
U.shape

(6, 6)

In [62]:
S

array([4.4381869 , 1.9794466 , 1.46150254])

In [63]:
Vh

array([[ 0.21043675,  0.56756075,  0.79598441],
       [-0.34158069,  0.80558549, -0.48410191],
       [ 0.91599073,  0.17002007, -0.36339258]])